### ISSUE TITLE
有没有可以支持到IIS上的程序包

### ISSUE THREAD

**Issue by weiyan2012** [AIDotNet/NuGet.Next#2]
应该打包下可以直接部署到IIS上的安装包，
https://github.com/AIDotNet/NuGet.Next/releases/tag/v0.1.0
像 baget： https://github.com/loic-sharma/BaGet/releases/tag/v0.4.0-preview2

**Comment by 239573049** [comment]
https://github.com/AIDotNet/NuGet.Next/releases/tag/v0.1.1
这里提供的都是win，支持使用window Service，双击install.bat即可安装成window service
